// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn_taO-ZSTO5J-SUaDW-wyfLxUh5A2n3Y',
    appId: '1:971286786724:web:9b531959f90f68051dac31',
    messagingSenderId: '971286786724',
    projectId: 'brushing-habit',
    authDomain: 'brushing-habit.firebaseapp.com',
    storageBucket: 'brushing-habit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOI5fbUWqSbhymtv-bq8kohIi5ggP0JVQ',
    appId: '1:971286786724:android:d850e1085ef6df351dac31',
    messagingSenderId: '971286786724',
    projectId: 'brushing-habit',
    storageBucket: 'brushing-habit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfaIFDdcbe19ousgUmGaUkl9LFuH3H2M',
    appId: '1:971286786724:ios:71dd008bc8c9c8a61dac31',
    messagingSenderId: '971286786724',
    projectId: 'brushing-habit',
    storageBucket: 'brushing-habit.appspot.com',
    iosClientId: '971286786724-85ure0c33o2s63saup3aq5gqslti7dmh.apps.googleusercontent.com',
    iosBundleId: 'com.yuju.brushingHabit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXfaIFDdcbe19ousgUmGaUkl9LFuH3H2M',
    appId: '1:971286786724:ios:6cff0e89f362ee081dac31',
    messagingSenderId: '971286786724',
    projectId: 'brushing-habit',
    storageBucket: 'brushing-habit.appspot.com',
    iosClientId: '971286786724-dpeadt3bu9pmonekuaati3uj0mgoglk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.brushingHabit',
  );
}
